# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\vektorel\Documents\GitHub\temelproje\IBRAHIM\Pyqt5\UI\arayuz.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(251, 298)
        self.button = QtWidgets.QPushButton(Form)
        self.button.setGeometry(QtCore.QRect(20, 30, 75, 23))
        self.button.setObjectName("button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Örnek"))
        self.button.setText(_translate("Form", "Tıkla"))
