CREATE TABLE IF NOT EXISTS `YT_ST_SOZLUK` (
	`ST_ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`ST_ALAN_KODU`	INTEGER NOT NULL,
	`ST_ALAN_ADI`	TEXT NOT NULL,
	`ST_TABLO_KODU`	INTEGER NOT NULL
);


CREATE TABLE IF NOT EXISTS `YT_PER_BILGI` (
	`PER_ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`PER_ADI`	TEXT NOT NULL,
	`PER_SOYADI`	TEXT NOT NULL,
	`PER_IL`	INTEGER NOT NULL,
	`PER_ILCE`	INTEGER NOT NULL,
);


CREATE VIEW V_PARCA_LISTE as 
SELECT art.Name,alb.title,tra.name FROM artists AS art
INNER JOIN albums AS ALB
ON ART.artistId = alb.artistId
INNER JOIN tracks AS tra
ON TRA.albumId = alb.albumId;

SELECT * FROM V_PARCA_LISTE